import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1785463926929 implements MigrationInterface {
    name = 'InitialSchema1785463926929'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."clients_type_enum" AS ENUM('particulier', 'entreprise')`);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" "public"."clients_type_enum" NOT NULL DEFAULT 'particulier', "nom" character varying NOT NULL, "ice" character varying, "telephone" character varying, "email" character varying, "adresse" text, "solde" numeric(14,2) NOT NULL DEFAULT '0', "plafond_credit" numeric(14,2) NOT NULL DEFAULT '0', "actif" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "entreprises" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nom" character varying NOT NULL, "ice" character varying, "if_fiscal" character varying, "rc" character varying, "patente" character varying, "cnss" character varying, "adresse" text, "telephone" character varying, "email" character varying, "logo_url" character varying, "devise" character varying NOT NULL DEFAULT 'MAD', "plan_abonnement" character varying NOT NULL DEFAULT 'standard', "actif" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e22358220a9a964ed3a142f2539" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "succursales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "nom" character varying NOT NULL, "adresse" text, "telephone" character varying, "responsable_id" uuid, "actif" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_4670917e5ccefcf5b36096dc2e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories_produits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "nom" character varying NOT NULL, "parent_id" uuid, CONSTRAINT "PK_4121d6e9e0d3e7dfc92a7713d42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unites_mesure" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "nom" character varying NOT NULL, "symbole" character varying NOT NULL, CONSTRAINT "PK_76b57d5e5444786308676febeb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."produits_type_enum" AS ENUM('produit', 'service')`);
        await queryRunner.query(`CREATE TABLE "produits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "categorie_id" uuid, "unite_id" uuid, "type" "public"."produits_type_enum" NOT NULL DEFAULT 'produit', "reference" character varying, "code_barre" character varying, "nom" character varying NOT NULL, "description" text, "prix_achat_ht" numeric(14,2) NOT NULL DEFAULT '0', "prix_vente_ht" numeric(14,2) NOT NULL DEFAULT '0', "taux_tva" numeric(5,2) NOT NULL DEFAULT '20', "seuil_alerte" numeric(14,3) NOT NULL DEFAULT '0', "gere_stock" boolean NOT NULL DEFAULT true, "image_url" character varying, "actif" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_738095029a8d184b11939537702" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40002c09f1af745a8819982840" ON "produits" ("entreprise_id", "code_barre") `);
        await queryRunner.query(`CREATE TABLE "lignes_vente" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vente_id" uuid NOT NULL, "produit_id" uuid NOT NULL, "quantite" numeric(14,3) NOT NULL, "prix_unitaire_ht" numeric(14,2) NOT NULL, "taux_tva" numeric(5,2) NOT NULL, "remise_pct" numeric(5,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_c1ec00c5d45a0f9e5900be90629" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ventes_statut_enum" AS ENUM('brouillon', 'validee', 'payee', 'annulee')`);
        await queryRunner.query(`CREATE TABLE "ventes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "succursale_id" uuid NOT NULL, "client_id" uuid, "user_id" uuid, "numero" character varying NOT NULL, "statut" "public"."ventes_statut_enum" NOT NULL DEFAULT 'brouillon', "total_ht" numeric(14,2) NOT NULL DEFAULT '0', "total_tva" numeric(14,2) NOT NULL DEFAULT '0', "total_ttc" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_f2ab45fd7d5872486d54499501d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "module" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid, "nom" character varying NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "succursale_id" uuid, "role_id" uuid, "nom_complet" character varying NOT NULL, "email" character varying NOT NULL, "mot_de_passe" character varying NOT NULL, "telephone" character varying, "actif" boolean NOT NULL DEFAULT true, "deux_fa_active" boolean NOT NULL DEFAULT false, "derniere_connexion" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_sav_priorite_enum" AS ENUM('basse', 'normale', 'haute', 'urgente')`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_sav_statut_enum" AS ENUM('ouvert', 'en_cours', 'resolu', 'ferme')`);
        await queryRunner.query(`CREATE TABLE "tickets_sav" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "client_id" uuid, "produit_id" uuid, "sujet" character varying NOT NULL, "description" text, "priorite" "public"."tickets_sav_priorite_enum" NOT NULL DEFAULT 'normale', "statut" "public"."tickets_sav_statut_enum" NOT NULL DEFAULT 'ouvert', "assigne_a" uuid, CONSTRAINT "PK_945cd721f719410bffa107b9954" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commentaires_ticket" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid NOT NULL, "user_id" uuid, "message" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c53de32f296f29b8ded9d02722c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sauvegardes_statut_enum" AS ENUM('en_cours', 'reussie', 'echouee')`);
        await queryRunner.query(`CREATE TABLE "sauvegardes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "fichier_url" character varying, "taille_octets" bigint, "statut" "public"."sauvegardes_statut_enum" NOT NULL DEFAULT 'en_cours', "message_erreur" text, CONSTRAINT "PK_b69a9dc2c90cbdfe2f9b87bbb8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "nom_complet" character varying NOT NULL, "poste" character varying, "telephone" character varying, "email" character varying, "date_embauche" date, "salaire_base" numeric(14,2) NOT NULL DEFAULT '0', "actif" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_68b60872017654daffdce387dd4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fiches_paie" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "employe_id" uuid NOT NULL, "periode" character varying NOT NULL, "salaire_base" numeric(14,2) NOT NULL, "primes" numeric(14,2) NOT NULL DEFAULT '0', "deductions" numeric(14,2) NOT NULL DEFAULT '0', "salaire_net" numeric(14,2) NOT NULL, CONSTRAINT "PK_9cd4f45a66928a640e73026113c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."conges_type_enum" AS ENUM('paye', 'maladie', 'sans_solde', 'autre')`);
        await queryRunner.query(`CREATE TYPE "public"."conges_statut_enum" AS ENUM('en_attente', 'approuve', 'refuse')`);
        await queryRunner.query(`CREATE TABLE "conges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "employe_id" uuid NOT NULL, "type" "public"."conges_type_enum" NOT NULL DEFAULT 'paye', "date_debut" date NOT NULL, "date_fin" date NOT NULL, "statut" "public"."conges_statut_enum" NOT NULL DEFAULT 'en_attente', "motif" text, CONSTRAINT "PK_d93df054c0a96a66be2ae990537" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "succursale_id" uuid NOT NULL, "produit_id" uuid NOT NULL, "quantite" numeric(14,3) NOT NULL DEFAULT '0', CONSTRAINT "UQ_6d89e3aabab7bf05f579d7060e0" UNIQUE ("succursale_id", "produit_id"), CONSTRAINT "PK_b5b1ee4ac914767229337974575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mouvements_stock_type_enum" AS ENUM('entree', 'sortie', 'transfert', 'ajustement', 'inventaire')`);
        await queryRunner.query(`CREATE TABLE "mouvements_stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "succursale_id" uuid NOT NULL, "produit_id" uuid NOT NULL, "type" "public"."mouvements_stock_type_enum" NOT NULL, "quantite" numeric(14,3) NOT NULL, "quantite_avant" numeric(14,3), "quantite_apres" numeric(14,3), "reference_doc" character varying, "motif" text, "user_id" uuid, CONSTRAINT "PK_506ce6b1ec2811fe36a9a131a14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plugins_installes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "code_plugin" character varying NOT NULL, "version" character varying, "configuration" jsonb NOT NULL DEFAULT '{}', "actif" boolean NOT NULL DEFAULT true, "installe_le" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_52108a8c9adb5e45836583d47ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."paiements_document_type_enum" AS ENUM('vente', 'achat')`);
        await queryRunner.query(`CREATE TYPE "public"."paiements_moyen_paiement_enum" AS ENUM('cash', 'tpe', 'virement', 'cheque', 'mobile_wallet', 'qr_code')`);
        await queryRunner.query(`CREATE TYPE "public"."paiements_statut_enum" AS ENUM('accepte', 'refuse', 'annule', 'remboursement')`);
        await queryRunner.query(`CREATE TABLE "paiements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "document_type" "public"."paiements_document_type_enum" NOT NULL, "document_id" uuid NOT NULL, "moyen_paiement" "public"."paiements_moyen_paiement_enum" NOT NULL, "montant" numeric(14,2) NOT NULL, "reference_transaction" character varying, "carte_4_derniers" character varying(4), "banque" character varying, "statut" "public"."paiements_statut_enum" NOT NULL DEFAULT 'accepte', "succursale_id" uuid, "user_id" uuid, CONSTRAINT "PK_d7a1e0ef2ae0e3a50cc4f41c35e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comptes_bancaires" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "banque" character varying NOT NULL, "rib" character varying, "solde" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_a40b0d7b8afb2fa2c9f1fec2831" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cheques_type_enum" AS ENUM('recu', 'emis')`);
        await queryRunner.query(`CREATE TYPE "public"."cheques_statut_enum" AS ENUM('en_attente', 'encaisse', 'rejete')`);
        await queryRunner.query(`CREATE TABLE "cheques" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" "public"."cheques_type_enum" NOT NULL, "numero_cheque" character varying, "banque" character varying, "montant" numeric(14,2) NOT NULL, "date_emission" date, "date_encaissement" date, "statut" "public"."cheques_statut_enum" NOT NULL DEFAULT 'en_attente', "tiers_id" uuid, CONSTRAINT "PK_b87771b4d5f52b7e5bf4498e912" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('info', 'alerte', 'erreur', 'stock_bas', 'paiement')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "titre" character varying NOT NULL, "message" text, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'info', "lue" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ia_previsions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "periode" character varying NOT NULL, "valeur_prevue" numeric(14,2) NOT NULL, "donnees_json" jsonb, CONSTRAINT "PK_8b0f99819f1ee1ed27832f8bd9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ia_documents_analyses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type_document" character varying, "texte_extrait" text, "confiance" numeric(5,2), "statut" character varying NOT NULL DEFAULT 'traite', CONSTRAINT "PK_7261d01e61058b7a8576fe08421" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."documents_commerciaux_type_enum" AS ENUM('devis', 'proforma', 'bon_livraison', 'facture', 'avoir')`);
        await queryRunner.query(`CREATE TYPE "public"."documents_commerciaux_statut_enum" AS ENUM('brouillon', 'envoye', 'accepte', 'refuse', 'converti', 'annule')`);
        await queryRunner.query(`CREATE TABLE "documents_commerciaux" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" "public"."documents_commerciaux_type_enum" NOT NULL, "numero" character varying NOT NULL, "client_id" uuid, "document_origine_id" uuid, "vente_id" uuid, "statut" "public"."documents_commerciaux_statut_enum" NOT NULL DEFAULT 'brouillon', "total_ht" numeric(14,2) NOT NULL DEFAULT '0', "total_tva" numeric(14,2) NOT NULL DEFAULT '0', "total_ttc" numeric(14,2) NOT NULL DEFAULT '0', "date_document" date NOT NULL, "date_echeance" date, CONSTRAINT "PK_6aebe726069ca0cddd4cd7b5f54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lignes_document" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "produit_id" uuid, "designation" character varying, "quantite" numeric(14,3) NOT NULL, "prix_unitaire_ht" numeric(14,2) NOT NULL, "taux_tva" numeric(5,2) NOT NULL, "remise_pct" numeric(5,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_b5fdbf4488911f2f1b095eeaddb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."factures_electroniques_statut_dgi_enum" AS ENUM('en_attente', 'valide', 'rejete', 'reemis')`);
        await queryRunner.query(`CREATE TABLE "factures_electroniques" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "document_id" uuid NOT NULL, "uuid_dgi" character varying NOT NULL, "qr_code" text, "xml_signe" text, "statut_dgi" "public"."factures_electroniques_statut_dgi_enum" NOT NULL DEFAULT 'en_attente', "date_envoi" TIMESTAMP WITH TIME ZONE, "date_validation" TIMESTAMP WITH TIME ZONE, "message_erreur" text, CONSTRAINT "UQ_8d3dc0fe45e5689125d4a201cbc" UNIQUE ("uuid_dgi"), CONSTRAINT "PK_6a0e8be3e2c7aa9e38a8d6d0f0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plan_comptable" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "numero_compte" character varying NOT NULL, "libelle" character varying NOT NULL, "type_compte" character varying, CONSTRAINT "PK_5af84d4003158c5ce194311033f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ecritures_comptables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "compte_id" uuid NOT NULL, "document_id" uuid, "debit" numeric(14,2) NOT NULL DEFAULT '0', "credit" numeric(14,2) NOT NULL DEFAULT '0', "date_ecriture" date NOT NULL, "libelle" text, CONSTRAINT "PK_d9c5bd8b51c271702b567d2a9ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."declarations_tva_statut_enum" AS ENUM('brouillon', 'deposee')`);
        await queryRunner.query(`CREATE TABLE "declarations_tva" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "periode" character varying NOT NULL, "tva_collectee" numeric(14,2) NOT NULL DEFAULT '0', "tva_deductible" numeric(14,2) NOT NULL DEFAULT '0', "tva_a_payer" numeric(14,2) NOT NULL DEFAULT '0', "statut" "public"."declarations_tva_statut_enum" NOT NULL DEFAULT 'brouillon', CONSTRAINT "PK_23b2e3b584bf29107a98aeb1514" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fournisseurs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "nom" character varying NOT NULL, "ice" character varying, "telephone" character varying, "email" character varying, "adresse" text, "solde" numeric(14,2) NOT NULL DEFAULT '0', "actif" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f1c487e8db913a007d534049f22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "journal_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid, "user_id" uuid, "action" character varying NOT NULL, "table_cible" character varying, "donnees" jsonb, "ip_adresse" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_26b79fb8b86a08630dacfdb4c0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parametres_entreprise" ("entreprise_id" uuid NOT NULL, "parametres" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_0be55cc9f4fdf4a3fcd3ebdb070" PRIMARY KEY ("entreprise_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."achats_statut_enum" AS ENUM('brouillon', 'validee', 'payee', 'annulee')`);
        await queryRunner.query(`CREATE TABLE "achats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entreprise_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "succursale_id" uuid NOT NULL, "fournisseur_id" uuid, "user_id" uuid, "numero" character varying NOT NULL, "statut" "public"."achats_statut_enum" NOT NULL DEFAULT 'brouillon', "total_ht" numeric(14,2) NOT NULL DEFAULT '0', "total_tva" numeric(14,2) NOT NULL DEFAULT '0', "total_ttc" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_f9bb09f128bec48e8685d0d73bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lignes_achat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "achat_id" uuid NOT NULL, "produit_id" uuid NOT NULL, "quantite" numeric(14,3) NOT NULL, "prix_unitaire_ht" numeric(14,2) NOT NULL, "taux_tva" numeric(5,2) NOT NULL, CONSTRAINT "PK_eb1a871e70382b51f53b02cd2f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "succursales" ADD CONSTRAINT "FK_22b06a7ed13e353833c9d38354f" FOREIGN KEY ("entreprise_id") REFERENCES "entreprises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories_produits" ADD CONSTRAINT "FK_22b845eadb00b19c38da7cc8b82" FOREIGN KEY ("parent_id") REFERENCES "categories_produits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produits" ADD CONSTRAINT "FK_ecb66b944bda31a8648741388d9" FOREIGN KEY ("categorie_id") REFERENCES "categories_produits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produits" ADD CONSTRAINT "FK_c84e71d2cd7029d60c71dc71658" FOREIGN KEY ("unite_id") REFERENCES "unites_mesure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lignes_vente" ADD CONSTRAINT "FK_26fb7472a621f6b590eee069f4d" FOREIGN KEY ("vente_id") REFERENCES "ventes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lignes_vente" ADD CONSTRAINT "FK_2ebb0eab3758ce22bb696560590" FOREIGN KEY ("produit_id") REFERENCES "produits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventes" ADD CONSTRAINT "FK_d8a1efb66930927ada2b9d996e9" FOREIGN KEY ("succursale_id") REFERENCES "succursales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventes" ADD CONSTRAINT "FK_392aeeaa978bb507c2a5096cdd1" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_963cb008522931a2275a71eb6a5" FOREIGN KEY ("succursale_id") REFERENCES "succursales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets_sav" ADD CONSTRAINT "FK_62946c18201f0ae77a6f33ebe54" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commentaires_ticket" ADD CONSTRAINT "FK_78d3f4d33db45a81d49349675d1" FOREIGN KEY ("ticket_id") REFERENCES "tickets_sav"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fiches_paie" ADD CONSTRAINT "FK_0e387bc4693fe14867ebff61d88" FOREIGN KEY ("employe_id") REFERENCES "employes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conges" ADD CONSTRAINT "FK_a910effc4a740655fa621faadab" FOREIGN KEY ("employe_id") REFERENCES "employes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "FK_05e5cf9ea9d01b4b8ab323de901" FOREIGN KEY ("succursale_id") REFERENCES "succursales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "FK_a5de9405bfd3b19e36176d42b9b" FOREIGN KEY ("produit_id") REFERENCES "produits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mouvements_stock" ADD CONSTRAINT "FK_58ba29006d6a731944665736447" FOREIGN KEY ("succursale_id") REFERENCES "succursales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mouvements_stock" ADD CONSTRAINT "FK_50e38e2b1df279583772258ec6f" FOREIGN KEY ("produit_id") REFERENCES "produits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents_commerciaux" ADD CONSTRAINT "FK_4ba8e34e87621e781c4cd2cd498" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lignes_document" ADD CONSTRAINT "FK_9343b0cb2636bc11bd9172c31bf" FOREIGN KEY ("document_id") REFERENCES "documents_commerciaux"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lignes_document" ADD CONSTRAINT "FK_4a70c7f1feae5f8e6cdf97693ed" FOREIGN KEY ("produit_id") REFERENCES "produits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecritures_comptables" ADD CONSTRAINT "FK_907122bca2a6bb462eb4daebf2e" FOREIGN KEY ("compte_id") REFERENCES "plan_comptable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achats" ADD CONSTRAINT "FK_e24011d9fb64cded4fa49df23eb" FOREIGN KEY ("succursale_id") REFERENCES "succursales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achats" ADD CONSTRAINT "FK_cddf0d9b3bbfffee40c48786516" FOREIGN KEY ("fournisseur_id") REFERENCES "fournisseurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lignes_achat" ADD CONSTRAINT "FK_c507a300e80b0d007a6690d6379" FOREIGN KEY ("achat_id") REFERENCES "achats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lignes_achat" ADD CONSTRAINT "FK_e04c5d9f71f408dc20808de16fe" FOREIGN KEY ("produit_id") REFERENCES "produits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "lignes_achat" DROP CONSTRAINT "FK_e04c5d9f71f408dc20808de16fe"`);
        await queryRunner.query(`ALTER TABLE "lignes_achat" DROP CONSTRAINT "FK_c507a300e80b0d007a6690d6379"`);
        await queryRunner.query(`ALTER TABLE "achats" DROP CONSTRAINT "FK_cddf0d9b3bbfffee40c48786516"`);
        await queryRunner.query(`ALTER TABLE "achats" DROP CONSTRAINT "FK_e24011d9fb64cded4fa49df23eb"`);
        await queryRunner.query(`ALTER TABLE "ecritures_comptables" DROP CONSTRAINT "FK_907122bca2a6bb462eb4daebf2e"`);
        await queryRunner.query(`ALTER TABLE "lignes_document" DROP CONSTRAINT "FK_4a70c7f1feae5f8e6cdf97693ed"`);
        await queryRunner.query(`ALTER TABLE "lignes_document" DROP CONSTRAINT "FK_9343b0cb2636bc11bd9172c31bf"`);
        await queryRunner.query(`ALTER TABLE "documents_commerciaux" DROP CONSTRAINT "FK_4ba8e34e87621e781c4cd2cd498"`);
        await queryRunner.query(`ALTER TABLE "mouvements_stock" DROP CONSTRAINT "FK_50e38e2b1df279583772258ec6f"`);
        await queryRunner.query(`ALTER TABLE "mouvements_stock" DROP CONSTRAINT "FK_58ba29006d6a731944665736447"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "FK_a5de9405bfd3b19e36176d42b9b"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "FK_05e5cf9ea9d01b4b8ab323de901"`);
        await queryRunner.query(`ALTER TABLE "conges" DROP CONSTRAINT "FK_a910effc4a740655fa621faadab"`);
        await queryRunner.query(`ALTER TABLE "fiches_paie" DROP CONSTRAINT "FK_0e387bc4693fe14867ebff61d88"`);
        await queryRunner.query(`ALTER TABLE "commentaires_ticket" DROP CONSTRAINT "FK_78d3f4d33db45a81d49349675d1"`);
        await queryRunner.query(`ALTER TABLE "tickets_sav" DROP CONSTRAINT "FK_62946c18201f0ae77a6f33ebe54"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_963cb008522931a2275a71eb6a5"`);
        await queryRunner.query(`ALTER TABLE "ventes" DROP CONSTRAINT "FK_392aeeaa978bb507c2a5096cdd1"`);
        await queryRunner.query(`ALTER TABLE "ventes" DROP CONSTRAINT "FK_d8a1efb66930927ada2b9d996e9"`);
        await queryRunner.query(`ALTER TABLE "lignes_vente" DROP CONSTRAINT "FK_2ebb0eab3758ce22bb696560590"`);
        await queryRunner.query(`ALTER TABLE "lignes_vente" DROP CONSTRAINT "FK_26fb7472a621f6b590eee069f4d"`);
        await queryRunner.query(`ALTER TABLE "produits" DROP CONSTRAINT "FK_c84e71d2cd7029d60c71dc71658"`);
        await queryRunner.query(`ALTER TABLE "produits" DROP CONSTRAINT "FK_ecb66b944bda31a8648741388d9"`);
        await queryRunner.query(`ALTER TABLE "categories_produits" DROP CONSTRAINT "FK_22b845eadb00b19c38da7cc8b82"`);
        await queryRunner.query(`ALTER TABLE "succursales" DROP CONSTRAINT "FK_22b06a7ed13e353833c9d38354f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "lignes_achat"`);
        await queryRunner.query(`DROP TABLE "achats"`);
        await queryRunner.query(`DROP TYPE "public"."achats_statut_enum"`);
        await queryRunner.query(`DROP TABLE "parametres_entreprise"`);
        await queryRunner.query(`DROP TABLE "journal_audit"`);
        await queryRunner.query(`DROP TABLE "fournisseurs"`);
        await queryRunner.query(`DROP TABLE "declarations_tva"`);
        await queryRunner.query(`DROP TYPE "public"."declarations_tva_statut_enum"`);
        await queryRunner.query(`DROP TABLE "ecritures_comptables"`);
        await queryRunner.query(`DROP TABLE "plan_comptable"`);
        await queryRunner.query(`DROP TABLE "factures_electroniques"`);
        await queryRunner.query(`DROP TYPE "public"."factures_electroniques_statut_dgi_enum"`);
        await queryRunner.query(`DROP TABLE "lignes_document"`);
        await queryRunner.query(`DROP TABLE "documents_commerciaux"`);
        await queryRunner.query(`DROP TYPE "public"."documents_commerciaux_statut_enum"`);
        await queryRunner.query(`DROP TYPE "public"."documents_commerciaux_type_enum"`);
        await queryRunner.query(`DROP TABLE "ia_documents_analyses"`);
        await queryRunner.query(`DROP TABLE "ia_previsions"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "cheques"`);
        await queryRunner.query(`DROP TYPE "public"."cheques_statut_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cheques_type_enum"`);
        await queryRunner.query(`DROP TABLE "comptes_bancaires"`);
        await queryRunner.query(`DROP TABLE "paiements"`);
        await queryRunner.query(`DROP TYPE "public"."paiements_statut_enum"`);
        await queryRunner.query(`DROP TYPE "public"."paiements_moyen_paiement_enum"`);
        await queryRunner.query(`DROP TYPE "public"."paiements_document_type_enum"`);
        await queryRunner.query(`DROP TABLE "plugins_installes"`);
        await queryRunner.query(`DROP TABLE "mouvements_stock"`);
        await queryRunner.query(`DROP TYPE "public"."mouvements_stock_type_enum"`);
        await queryRunner.query(`DROP TABLE "stocks"`);
        await queryRunner.query(`DROP TABLE "conges"`);
        await queryRunner.query(`DROP TYPE "public"."conges_statut_enum"`);
        await queryRunner.query(`DROP TYPE "public"."conges_type_enum"`);
        await queryRunner.query(`DROP TABLE "fiches_paie"`);
        await queryRunner.query(`DROP TABLE "employes"`);
        await queryRunner.query(`DROP TABLE "sauvegardes"`);
        await queryRunner.query(`DROP TYPE "public"."sauvegardes_statut_enum"`);
        await queryRunner.query(`DROP TABLE "commentaires_ticket"`);
        await queryRunner.query(`DROP TABLE "tickets_sav"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_sav_statut_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_sav_priorite_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "ventes"`);
        await queryRunner.query(`DROP TYPE "public"."ventes_statut_enum"`);
        await queryRunner.query(`DROP TABLE "lignes_vente"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40002c09f1af745a8819982840"`);
        await queryRunner.query(`DROP TABLE "produits"`);
        await queryRunner.query(`DROP TYPE "public"."produits_type_enum"`);
        await queryRunner.query(`DROP TABLE "unites_mesure"`);
        await queryRunner.query(`DROP TABLE "categories_produits"`);
        await queryRunner.query(`DROP TABLE "succursales"`);
        await queryRunner.query(`DROP TABLE "entreprises"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP TYPE "public"."clients_type_enum"`);
    }

}
